### ISSUE TITLE
Electron reload not working

### ISSUE THREAD

**Issue by p3140** [maximegris/angular-electron#15]
Hi. First of all thanks for this great repository. Im pretty new working with Angular 4 so this problem may be because of that. 
The issue is that live reloading my app after changes in the code are done is not possible until i change app-routing.module.ts to this:
```
@NgModule({
    imports: [RouterModule.forRoot(routes, {useHash: true})],
    exports: [RouterModule]
})
```
Also i had to change index.html base href tag to be empty:
`<base href="">`
all this to tell angular to work with hashbang style routes instead of html5 style routes.

The solution came from [here](https://discuss.atom.io/t/angular-2-routes-breaking-on-electron-app-refresh/28370/3).

¿is this the right solution or i'm missing something?

Thanks in advance, gr33ts from Chile.

**Comment by maximegris** [comment]
Thanks for this report !
I pushed the fix.

Regards

**Comment by michaelb-01** [comment]
I think I’m having the same issue, is this the only solution? It would be nice to be able to configure electron to work with html5 location strategy (angular’s default)

**Comment by shivarajnaidu** [comment]
Yes... Is there any other solution for this to make things work with angular's default strategy

**Comment by Shaimae18** [comment]
2019 still working dude
Ng8

**Comment by CPrescher** [comment]
The change to   `<base href=''>` actually breaks reloading right now for routing without `useHash=true`.

It adds to every URL an extra backslash which cannot be resolved by the router e.g. it goes from "file" to "file/" which is quite annoying and it is hard to find out why this is happening.

I checked with electron and the reload seems to work for hashing and without it with the
`<base href='/'>` at least for angular 9

Since the latest version of this repo is supporting angular 9, would it be possible to change the base element back, since there is no need for the `href=''` anymore and it only will provide confusion for future users who also do not want to use hashing.

**Comment by maximegris** [comment]
@CPrescher You are right. The `base-href` should be declared with `/` in order to use both routing strategies (with or without fragments).

By the way this doesn't seems to work when the app is encapsulate in an electron executable (after running `electron:local` or `electron:linux` or `electron:windows` or `electron:mac`). 

To make it works, I had to set `--base-href ./` in npm `build` script.

I also added another page to check that the routing is correctly working.

**Comment by CPrescher** [comment]
Great, thank you for making this change so fast.

**Comment by maximegris** [comment]
You're welcome :)

**Comment by seiyria** [comment]
Is webpack supposed to reload the renderer when you change angular-related code? I'm not seeing webpack attempt to recompile anything when I change an html file.

**Comment by petef19** [comment]
Also cannot get this to work. my stack:

@ionic/cli@6.10.1
@ionic-native/core@5.26.0
@capacitor/core@2.2.0
electron@8.3.1
electron-reload@1.5.0

Had to employ the {useHash: true} option as well as set <base href="" /> to get manual reload working via ctrl+R. electron-reload itself never works on this stack.

If I add it top of Electron's index.js file (Capacitor renamed main.js to index.js) as per the example on the main page of this repo, then on every detected change the cursor starts flickering and an endless spinning circle appears next to the cursor until I close the Electron window... 

any idea how to fix this ? would love to have auto-reloads in Electron browser...

**Comment by mariotaku** [comment]
For people who still have this issue, do a force app load if failed:

```
win.webContents.on('did-fail-load', () => win.loadURL(...));
```

**Comment by rbalet** [comment]
> For people who still have this issue, do a force app load if failed:
> 
> ```
> win.webContents.on('did-fail-load', () => win.loadURL(...));
> ```

This will work, but you will loose the value of the variable because your app will be restarting. So if you need a log-in screen before you're able to run the electron app, be sure to store the value in the `localStorage` _or somewhere else_
