### ISSUE TITLE
Problem to get debugging working

### ISSUE THREAD

**Issue by vIceBerg** [maximegris/angular-electron#154]
Hi!

I just cloned the project. I try to follow the comments here:
https://github.com/maximegris/angular-electron/issues/84#issuecomment-357424682

But... I feel like a fool because I can't find any of the configuration specified.
I do not have the build:electron:main script part, I do not have the webpack.config.js file...

It looks like the debugging method/configs changed by the time this issue was opened and closed.

Is there a new step-by-step tutorial to get main process and child process debugging?

Thanks

VB

**Comment by williamJmelton** [comment]
I'd like to know why the serve command has been changed -- I just pulled from upstream on my fork and alot has changed. Can someone explain why?

I would also like to know how to debug now - if possible

**Comment by mo2menelzeiny** [comment]
@williamJmelton, v3.0.0 was a breaking change to this project, the build process was migrated to using angular cli rather than webpack, which I recommended because it supports AOT compilation as well as faster and more stable builds. It also makes it easier to migrate to newer Angular releases as they roll out.
Also other changes where done on the environment configuration check the most recent commits for more details.

**Comment by maximegris** [comment]
As mo2menelzeiny said, v3.0.0 was a breaking change of how project runs (I'll try to find time to add a changelog file :/) 

In v2.x, webpack config was ejected of angular project. This means more customization possible, but a lot of pain when I had to migrate to newest version of Angular/Electron.
That was the purpose of my refactoring in v3.x

**Comment by vIceBerg** [comment]
Hi!

It seams you answer williamJmelton comment/question, but the original one stays unanswered.

The original question was how to debug? Is there another step-by-step guide?

Thanks

**Comment by williamJmelton** [comment]
So if I pull from upstream at this point my app will break?
