### ISSUE TITLE
Feature Request[Auto Updater]

### ISSUE THREAD

**Issue by richard457** [maximegris/angular-electron#167]
Hello, there is many auto-updaters out there and because they are many this lead to confusing the right one, for example, the auto-update should ship an update to a user without use have to shout down the app it would be nice if we can have it within this project set in simple way.

**Comment by seopei** [comment]
I am using `electron-updater` (https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater). 
It is very easy to add to your project: https://www.electron.build/auto-update

**Comment by richard457** [comment]
Great, I like the docs @seopei provided however that would be nice if we can implement it here on this project so that we can have a common understanding on this issue and how do do it much better. Thank you again @seopei You saved me.

**Comment by seopei** [comment]
Sure not problem!
BTW with the `electron-updater` the user has to restart the app in order to get the newer version of the app.

The implementation is pretty simple and auto update depends on how you publish a new version of the, so I think it is not a good idea to implement a example in this project because of the variety of the different publisher.

For example I publish a new version of the app the Amazon S3:

install the publisher for Amazon S3:
```
npm i -D electron-publisher-s3
```

in main.ts:
```
const { autoUpdater } = require('electron-updater');
...
app.on('ready', () => {
   ...
  // this will check if there is a newer version of the app available and 
  // display the user a notification that the user has to restart the app in order to get the newer version
   autoUpdater.checkForUpdatesAndNotify(); 
  ...
});
```

add something like this in electron-builder.json:
```
"publish": {
    "provider": "s3",
    "bucket": "placeholder_bucket_name",
    "region": "eu-west-1",
    "path": "updates"
  }
```

if you are ready the publish a new version:
```
export AWS_ACCESS_KEY_ID=<your-aws-access-key-id>
export AWS_SECRET_ACCESS_KEY=<your-secret-access-key>
npx electron-builder build --mac --publish always
```

more documentation to publish your app: https://www.electron.build/configuration/publish

Maybe we can add these instruction to the `README.md`.

**NOTE:** auto updates are not working with `portable` builds of your app!

**Comment by richard457** [comment]
In That case we may choose github as open source just to provide a clear
clue

Richard Muragijimana

**Comment by wehrstedt** [comment]
@seopei If I setup my configuration like you posted above, I get the following error:
``` 
electron-builder 19.45.4
Using electron-builder.json configuration file
No native production dependencies
Packaging for win32 x64 using electron 1.7.8 to app-builds\win-unpacked
Error: Application entry file "main.js" in the "E:\electron-server-console\app-builds\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
    at error (E:\electron-server-console\node_modules\electron-builder\src\asar\asarFileChecker.ts:7:12)
    at E:\electron-server-console\node_modules\electron-builder\src\asar\asarFileChecker.ts:33:11
    at Generator.next (<anonymous>)
    at E:\electron-server-console\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at checkFileInArchive (E:\electron-server-console\node_modules\electron-builder\out\asar\asarFileChecker.js:46:21)
    at E:\electron-server-console\node_modules\electron-builder\src\platformPackager.ts:316:13
    at Generator.next (<anonymous>)
```

Any ideas?

**Comment by maximegris** [comment]
Thanks for your answer @seopei :)
