### ISSUE TITLE
Support disabled nodeIntegration

### ISSUE THREAD

**Issue by njordblock** [maximegris/angular-electron#262]
I have tried to disable nodeIntegration for increased security but it seems to affect e.g. Polyfills and more and result in a series of exceptions which is hard to intercept (e.g. require() in runtime.js).

Any suggestions on how to use the boilerplate with nodeIntegration disabled? The concept would be to import the neccessary node-modules in the preload script and then access them from the electron-service later as they would be available in global/window.

`webPreferences: {
      nodeIntegration: false,
      preload:path.join(__dirname, 'dist/preload.js')
    }`

Thanks in advance!

**Comment by frjonsen** [comment]
Also having issues with this. Using `webPreferences: { nodeIntegration: false }` breaks the `start` command. However, if I change it to run `postinstall:web` instead of `postinstall:electron` it seems to work. Still having been using this template (or electron in general, for that matter) to know what this might break though.
