### ISSUE TITLE
Questions regarding postinstall-* and postcss

### ISSUE THREAD

**Issue by appsolutegeek** [maximegris/angular-electron#297]
Hi,

Great project !!  I would like to know why postintall-* is being called and whats the reason for it - I am sure its necessary but I don't fully understand why - It would help to try and understand it.

Also, postcss config, where is this integrated or being called from?

Thanks in advance

**Comment by whyboris** [comment]
I was recently confused about [postcss.config.js](https://github.com/maximegris/angular-electron/blob/master/postcss.config.js) as well. I suspect it's just a spandrel from earlier versions of this repository (before _Angular 7_). I suspect it's there in case someone wants to use the [postcss](https://github.com/postcss/postcss) functionality but can be safely deleted otherwise.

@maximegris - comments? 😃

**Comment by maximegris** [comment]
Indeed postcss is an old file and can be safely deleted.

To answer @appsolutegeek about postinstall-* files, they are used by some npm scripts in `package.json` to make the project work on web or electron environment.

**Comment by jambulud** [comment]
Hi,

In my project I have removed the postinstall-* files and modified the scripts in package.json acordingly (removed  "npm run postinstall:electron &&", "npm run postinstall:web &&" ) but everything seems to be working fine so I don't know if I'm missing something. Could you please tell me which error I should expect? 

Thanks
