### ISSUE TITLE
Connect to Oracle database by oracledb

### ISSUE THREAD

**Issue by FantomHunter** [maximegris/angular-electron#299]
Hi all,
I'm trying to connect to Oracle database by using the library "oracledb"
https://www.npmjs.com/package/oracledb
and use this lib to apply the typscript:
https://www.npmjs.com/package/@types/oracledb
Currently, with electron-starter using js, I connect to database successfully. But when I apply to angular-electron, it's always fails with this log:
Uncaught Error: NJS-045: cannot load the oracledb add-on binary for Node.js 10.2.0 (win32, x64)
Cannot find module E:\Personal\Learning\TechnicalSkill\electron\test\angular-electron-angular6\node_modules\electron\dist\resources\electron.asar\build\Release\oracledb.node
Node-oracledb installation instructions: https://oracle.github.io/node-oracledb/INSTALL.html
You must have 64-bit Oracle client libraries in your PATH environment variable.
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from
http://www.oracle.com/technetwork/topics/winx64soft-089540.html
A Microsoft Visual Studio Redistributable suitable for your Oracle client library version must be available.

    at Object../node_modules/oracledb/lib/oracledb.js (oracledb.js:53)
    at __webpack_require__ (bootstrap:76)
    at Object../node_modules/oracledb/index.js (index.js:1)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/components/home/home.component.ts (main.js:5957)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/app-routing.module.ts (main.js:5724)
    at __webpack_require__ (bootstrap:76)
    at Object../src/app/app.module.ts (app.component.ts:11)
    at __webpack_require__ (bootstrap:76)

Anyone have some experience with this lib?
Thanks in advance :)

**Comment by thepepto** [comment]
@FantomHunter I have used node-oracledb quite a few times and am not a huge fan of the "installation requirement" of the library. In a nutshell, as stated in the INSTALL.html link you listed, you need to have the Basic Package extracted "somewhere" on the client AND the `./lib` directory mapped to the system path. It becomes more complicated in the angular-electron world since you could be targeting multiple platforms.

I hope someone has more experience on custom installations which is likely what is required here. Just wanted to share my pain relief once I understood the requirement on the library for the error you listed 
e.g. A `./lib` folder extracted from Basic Client Oracle Package was not found in the system path.

**Comment by rbocchi** [comment]
I am facing the same problem.
