### ISSUE TITLE
Why all packages are in devDependencies?

### ISSUE THREAD

**Issue by Cefold** [maximegris/angular-electron#345]
There are some packages like "@types/*" in devDependencies, that's easy to understand, but why packages like "rxjs", "@angular/*" are also in devDependencies? 
The issue https://github.com/maximegris/angular-electron/issues/99 mentioned "they are being included as part of the webpack generated bundles already", can someone explain it a little bit, please?

**Comment by l1b3r** [comment]
Disclaimer: some exp in Angular but very little in Electron.

From what I understand, electron wraps your web application in its compiled form, i.e. after `ng build` (or any of uts variations) is performed. At this point, all the angular modules (`@angular/...`) and any other app deps (rxjs, charting libraries, custom components etc.) are already baked into the minified and uglified bundles that are represented by the javascript files that are generated in your `dist/` directory.

When electron-builder compiles the app into an actual executable, it takes whatever `ng build` has produced, which is already a functioning angular application that you can theoretically run in the browser (with a couple of irrelevant limitations). Apart from that, it will also add anything you put in `dependencies` in `package.json` to the resulting executable (at the same time ignoring `devDependencies`). So adding any Angular deps or your app deps to `dependencies` would be a dead weight since your Angular app is already transpiled into JS with those deps "dissolved" in the javascript files.

Please correct me if I'm wrong or missing something.

**Comment by maximegris** [comment]
You're right @l1b3r ! Thanks for the answer 👍
