### ISSUE TITLE
Spectron + Protractor

### ISSUE THREAD

**Issue by FrancescoBorzi** [maximegris/angular-electron#348]
Are there any plans to attach Protractor to the Spectron session in order to use it to run tests?

For example: https://github.com/electron/spectron/issues/164#issuecomment-286328622

**Comment by FrancescoBorzi** [comment]
the issue is still valid

**Comment by FrancescoBorzi** [comment]
still valid

**Comment by FrancescoBorzi** [comment]
still valid

**Comment by FrancescoBorzi** [comment]
still valid

**Comment by FrancescoBorzi** [comment]
@maximegris can you make it stop?

**Comment by FrancescoBorzi** [comment]
@maximegris

**Comment by EngJay** [comment]
I've run into a use case for this, too - some components from Angular Material seem to be impossible or at least problematic to test with the baseline e2e setup of the angular-electron template due to [the need to use the test harnesses provided with the components](https://material.angular.io/guide/using-component-harnesses), which happen to be written only for Protractor in the e2e context. These components seem to be at least partially invisible to Spectron/Webdriver.

I'm considering an attempt to implement Protractor tests to cover just the parts of our application that use Angular Material components but I'm also concerned it will lead to excessive maintenance overhead due to the increase in testing frameworks in use for one application.
