### ISSUE TITLE
Not able to use nebular components

### ISSUE THREAD

**Issue by vijhhh2** [maximegris/angular-electron#361]
Not able to configure to nebular components

**Comment by nikhilnxvverma1** [comment]
More details?
All external libraries, frameworks, web components, etc. have to be configured in angular.json under scripts and styles array for the right project.

**Comment by Sherloks** [comment]
Try update your Angular.json and move the Angular libraries from devDependencies to dependencies

**Comment by roobychan** [comment]
I have similar issue with turly ui.
in angular.json
`"styles": [
              "src/styles.scss",
              "node_modules/@angular/cdk/overlay-prebuilt.css",
              "node_modules/truly-ui/css/icons/dx-icons/css/icons.scss",
              "node_modules/truly-ui/css/icons/fa-icons/css/icons.scss",
              "node_modules/truly-ui/css/icons/ion-icons/css/icons.scss",
              "node_modules/truly-ui/css/icons/animations.scss"
            ],`
app.module.ts
`import 'reflect-metadata';
import '../polyfills';

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClientModule, HttpClient } from '@angular/common/http';
import { CoreModule } from './core/core.module';
import { SharedModule } from './shared/shared.module';

import { AppRoutingModule } from './app-routing.module';

// NG Translate
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

import { HomeModule } from './home/home.module';

import { AppComponent } from './app.component';
// import { CoreModule } as TCoreModule from 'truly-ui';
// import { InputModule, ButtonModule } from 'truly-ui'; // Import Modules
import * as TUI from 'truly-ui';


// AoT requires an exported function for factories
export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,
    CoreModule,
    SharedModule,
    HomeModule,
    AppRoutingModule,
    TUI.CoreModule.forRoot({theme: 'default'}), // Configurations
    TUI.InputModule,
    TUI.ButtonModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpClient]
      }
    })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}
`
Still I got error in console
Can't bind to 'placeholder' since it isn't a known property of 'tl-input'.
1. If 'tl-input' is an Angular component and it has 'placeholder' input, then verify that it is part of this module.
2. If 'tl-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    ngModel="Many Properties"
    [iconBefore]="'ion-printer'"
    [ERROR ->][placeholder]="'With Placeholder'"
    [textAfter]="'US'"
    [clearButton]="true"
"): ng:///HomeModule/HomeComponent.html@10:4
