### ISSUE TITLE
A JavaScript Error Occurred in the main process

### ISSUE THREAD

**Issue by astroame** [maximegris/angular-electron#363]
I am having a problem running my angular-electron desktop app after successfully building the .exe file on Windows using this CLI Command:

    npm run electron:windows

I got the error 

> Javascript error occurred in the main process   
Uncaught Exception:   
Error: Cannot find module './src/app/models/user.model'   

I could not found any solution on the github repo: https://github.com/maximegris/angular-electron

main.ts   file

    import { app, BrowserWindow, screen, ipcMain } from 'electron';
    import * as path from 'path';
    import * as url from 'url';
    import { createConnection, getConnection } from 'typeorm';
    import { User } from './src/app/models/user.model';

How do I set the path to the user.model.ts file located at src/app/models/user.model so that electron can find it when the app is build for release.

NOTE: everything works fine during development.

**Comment by nikhilnxvverma1** [comment]
When you package the app, the 'electron-builder.json' file dictates what gets bundled up for the MAIN process. If you notice carefully, everything under src is excluded in the 'files' array (`!src/`). That's where your user.model resides which is why it is unable to package that in. Everything works flawlessly in development because you are working in bare relative directories. 

You can fix this by changing file location, duplicating the file or simply making an exception for the file in electron-builder.json.

**Comment by astroame** [comment]
Please can you give a sample code on how to make exception for the file  in electron-builder.json.
file:  `'./src/app/models/user.model'`

**Comment by nikhilnxvverma1** [comment]
In electron-builder.json, inside the `files` array, add an entry for `user.model`. Try something like :

`src/app/models/user.model.js`

As per the listing in the array, all typescript files are excluded. In the above case I am assuming that all compiled typescript files output to the same directory. The array items use glob patterns so you just need to make a successful inclusion(exception) for your file. You can even make inclusions for complete directories (hint: `src/app/models`)

**Comment by astroame** [comment]
Thanks so much @nikhilnxvverma1 , i actually changed the file location to a folder outside `src/` and it works flawlessly. Thanks.

But now i have a new issue:  here is it ; [#366]
