### ISSUE TITLE
How can I listen the `main.ts` file changes for hot reload?

### ISSUE THREAD

**Issue by mehmet-erim** [maximegris/angular-electron#424]

**Comment by Css-IanM** [comment]
@mehmet-erim 'main.ts' for the electron process cannot be hot reloaded. The process can only be restarted. See #209

**Comment by Css-IanM** [comment]
You can use something like nodemon with monitoring the main process files, in which case you will need to change the scripts in package.json to run accordingly and find some way to distinguish the files only related to the main process, ie create a directory for them and update the scripts and paths accordingly and tell nodemon to monitor and restart it for you. Otherwise you will need to restart that process yourself when you make changes.

**Comment by mehmet-erim** [comment]
Thanks @Css-IanM 

I added two scripts.

```bash
"nodemon": "nodemon --exec 'yarn electron:serve' ./main.ts",
"start:watch": "npm-run-all -p ng:serve nodemon",
```
These are enough for me 👍
