### ISSUE TITLE
bootstrap app from dist directory

### ISSUE THREAD

**Issue by Suroor-Ahmmad** [maximegris/angular-electron#522]
Hi, I'm building application which has nodejs running within, I'm programming using typescript and I have too many ts files in my application. I want ts compiled files to be placed in separate directory like `dist`, but I found `outDir` removed from `tsconfig.serve.json` file.
Is it possible to serve from dist directory during development so I can keep my project directory neat?

**Comment by Suroor-Ahmmad** [comment]
I was able to achieve this hence closing.

If you are looking answer,
Modified below 3 files,
added `outDir: "./dist/"` in `tsconfig.serve.json` 
modified `main: "./dist/main.js" in `package.json'
modified `main.ts`

    require('electron-reload')(__dirname, {
            electron: require(`${process.cwd()}/node_modules/electron`)
    });

**Comment by Chifilly** [comment]
I don't know if you ran into this issue, but I had an issue that when you built the app for production, it would fail, because TypeScript builds the Electron side of things into `dist`, but then when Angular builds for production it deletes `dist` for the Angular files, so then all the Electron files are gone with it. I tried re-ordering the build process so tsc runs before ng, but that also broke everything (I clearly don't fully understand the build process).

What I did to remedy this was (and will hopefully help people in the same situation);
- in `tsconfig.serve.json` set `outDir` to `./dist-electron`
- in `package.json` set `main` to `./dist-electron/main.js`

This will put all the Electron files into its own `dist-electron` folder, which ng build won't interfere with
