### ISSUE TITLE
Require("url") is not defined

### ISSUE THREAD

**Issue by FearGannicus** [maximegris/angular-electron#563]
I know there were other issues opened and resolved regarding this issue. I just had some questions regarding it. I am currently making a website, and an application as well using this repository. 

Running this in web mode instead of production does resolve the issues, but I guess my question is why? I never saw an explanation on why this application has issues with production mode. 

![image](https://user-images.githubusercontent.com/43388217/102439657-9f289200-3fec-11eb-8423-abd63228277d.png)

What is the differences between production and web? I notice that there's obfuscation/minification with the production mode and not with web, does that cause any differences between how the code is ran? 

Hopefully this makes sense, I am just curious and trying to understand more. Thanks for any assistance in advance lads <3

**Comment by dodois** [comment]
1. Create a fake ```require.js```

```javascript
module.exports.fakeRequire = (m) => {
  return typeof global.require == "function"
    ? global.require(m)
    : typeof window == "undefined"
    ? require(m)
    : window.require(m);
};
```
2. Use ```fakeRequire``` instead of ```require```
```javascript
const { fakeRequire } = require("../require");
const path = fakeRequire("path");
```

**Comment by FearGannicus** [comment]
@dodois I am not even sure where `require('url');` is being called from as it only happens in production mode for some strange reason.

**Comment by dodois** [comment]
https://github.com/maximegris/angular-electron/issues/563#issuecomment-751568025 Works for me

I have the same problem, after analysis I think it is caused by the wrong use of node modules in the rendering process, non-node modules will not have this problem

**Comment by s4m0r4m4** [comment]
Hi @FearGannicus, I feel that your question was never really answered here and I ran into a similar issue. Here's what I found out after digging through some stuff:

1) For me, the error was thrown from createSocketUrl.js, when it tries to `require('url')`. From your screenshot, it looks like this error is being thrown from minified code where the function names have been obsfucated, so it's hard to tell if it's coming from the same place or not, but I suspect it is.
2) createSocketUrl.js is a part of the npm package "webpack-dev-server", which is part of the angular web development server. This is loaded into the browser and run inside the browser javascript engine when doing development (you can read more about the Angular JIT compiler if you're unfamiliar with this).
3) The custom angular webpack config that is used in this repo handles the "web" config specially by setting the 'target' property of the webpack config to 'web'. This has significant downstream implications for how webpack bundles things (read more [HERE](https://webpack.js.org/configuration/target/))
4) So when you switch to the angular "web" target (whose name just happens to match that of the webpack target), it cascades downstream to affect how webpack is compiling code.
5) This only becomes a problem if I set `contextIsolation` to `true` or `nodeIntegration` to `false` (`nodeIntegration` is going away in favor of `contextIsolation`) in the webPreferences of the electron BrowserWindow. So the conflict appears to come from webpack targeting electron-renderer if you don't use the angular 'web' target, resulting in require statements being included in your renderer code and then Electron throws the error with `contextIsolation=true` because it isolates the renderer so it can't access node functions like `require`.

Hope that helps clear things up a bit!

**Comment by FearGannicus** [comment]
Hey @s4m0r4m4 thanks for reaching out and trying to help me a little bit with understanding why I was getting that error. 

I think I understand what you're saying, however, it seems I don't get the error in the actual `electron` window - things run nice and smoothly there using `production` mode. It seems it errors when not run inside of `electron`. 

As far as I can see it doesn't seem to matter much being compiled using the `web` target? I've had my website running now for a while using `web` so hopefully that's fine 🤣

**Comment by s4m0r4m4** [comment]
It works in production because angular uses AOT compilation, so it doesn't ship it's development code over to the browser which is what was causing the issue (if my guess is right). Compiling as the web target is what can make things work in development.
