### ISSUE TITLE
request: readme information about npm modules used in both angular and electron

### ISSUE THREAD

**Issue by crwgregory** [maximegris/angular-electron#599]
From my understanding of the readme there isn't any information on using a node module in both the front end "web" development and the Electron bundle. 

The readme describes using Electron and Node APIs depending on the deployment, and also how to add specific modules for angular by using the `--save-dev` flag, but it doesn't state the use case of needing the same module in both Electron and in Angular. 

Example:
I want to install `firebase` `npm i firebase` this will add it to my "dependencies" list. 
Now I can import my auth module in node and angular, but I only want **analytics** in Angular:
```
# main.ts
import * as auth from "firebase/auth";

# my.compomponent.ts
import * as auth from "firebase/auth";
import * as analytics from "firebase/analytics";

```

Will this
> significantly increase the size of [my] final package

?
https://github.com/maximegris/angular-electron#use-web-3rd-party-libraries-like-angular-material-bootstrap-

**Comment by maximegris** [comment]
Hi

I just changed how electron & web dependencies are loaded in the final bundle (with electron builder two packages feature).

So I was able to move all angular deps in  `dependencies` section instead of `devDependencies` without increase final bundle size.

Now there is two package.json : 
*  in root folder => the one used by renderer process (ie. Angular)
* in app/ folder => the one used by electron main process (ie NodeJS)

So now you can import your auth module in Node and Angular and only analytics in Angular.
