### ISSUE TITLE
Iframe

### ISSUE THREAD

**Issue by daniele-zurico** [maximegris/angular-electron#61]
Could I ask if it electron is working if you have an iframe that contains another andukar4 application?
Parent angular4, iframe angular4

**Comment by maximegris** [comment]
You can use an iframe if the application displayed in the iframe allow it.
Iframe has some disavantages in electron like running in the same process as the electron app.

Otherwise you an use electron `webview`. It displays external web content in an isolated frame and process.
 Check https://electron.atom.io/docs/api/webview-tag/

**Comment by daniele-zurico** [comment]
Sorry I’ve been to super precise.
My idea is that the iframe is again compiled with electron so we have:
1)container with webview/iframe -> compiled in electron
2) content -> compiled with electron
Final executable only one that contains both

**Comment by maximegris** [comment]
Well I have not the answer for such a use case, I suggest you to ask it directly in electron repo.
