### ISSUE TITLE
Paths created in tsconfig.json not work

### ISSUE THREAD

**Issue by vuggy17** [maximegris/angular-electron#649]
**Describe the bug**
I created path in tsconfig.json, then import module using that path, but compiler tells module not found

**To Reproduce**
1. Go to tsconfig.json
2. Add baseUrl and path
3. Go to app.module
4. Import that module

**Expected behavior**
Module imported using custom path

**Screenshots**
tsconfig,json
![image](https://user-images.githubusercontent.com/61084329/141233605-3ff83763-d6f4-44b5-b176-8f95fb17f26f.png)

app.module.ts
![image](https://user-images.githubusercontent.com/61084329/141233498-91556e23-9353-4172-aca9-5a88c9736a9e.png)

**Additional context**
 - project stucture:
![image](https://user-images.githubusercontent.com/61084329/141233668-70dfc722-8084-471b-b06b-945c66d8fa89.png)

**Comment by maximegris** [comment]
Maybe you should try

```
    "paths": {
      "@shared/*": ["app/shared/*"],
    }
```

**Comment by whyboris** [comment]
@maximegris -- just in case you might have an idea about this (only look into this if you have interest and time).

I tried in my project, and `VS Code` correctly recognizes the paths, but when I run `npm start` it fails:

https://github.com/whyboris/Video-Hub-App/pull/752 <-- code change

`tsconfig.json` change:
https://github.com/whyboris/Video-Hub-App/pull/752/files#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0R7

The `npm start` tries to run using `tsconfig-serve.json` and gives this error:
> Cannot find module '@pipes' or its corresponding type declarations.

When I add the `paths` property to `tsconfig-serve.json` (I need to add `./` before each path) but  I get this error:
> The 'import.meta' meta-property is only allowed when the '--module' option is 'es2020', 'es2022', 'esnext', 'system', 'node12', or 'nodenext'.

This is because I use a service worker:
> const worker = new Worker(new URL('./tags.worker', import.meta.url), { type: 'module' });

I suspect I might have to suck it up and have `../../../../../interfaces/` instead of `@my/` :trollface: 

But in case you instantly know what's going wrong with my project, please let me know 🙇

**Comment by a-rizzuti** [comment]
Did you find a solution?

**Comment by whyboris** [comment]
It's been over 2 years and it still doesn't work in my project 😔
Would appreciate anyone trying their hand at it 🙇‍♂️

**Comment by whyboris** [comment]
Tried again in my project - still doesn't work 🤦 
Not a problem with `angular-electron` 👌 
If anyone figures it out, I'd appreciate a comment / link on my PR: https://github.com/whyboris/Video-Hub-App/pull/752
