### ISSUE TITLE
config target in webpack is never used

### ISSUE THREAD

**Issue by MMcKester** [maximegris/angular-electron#721]
Hi, thanks for this great boilerplate template! I came across this line in the `angular.webpack.js` file:

```
config.target = 'electron-renderer'; 
```

The target was introduced in webpack for Electron related polyfills, configs, etc. but the value is seemingly always replaced by the proceeding if statement `if (config. fileReplacements)`.

Is this intentional or when is `electron-renderer` being passed on?

Thanks!

https://github.com/maximegris/angular-electron/blob/a3eeb6a953d3f178d68378c18478ae2e0fc02132/angular.webpack.js#L8-L22

**Comment by maximegris** [comment]
Hi

`electron-renderer` is only replaced when you build the app with angular `web` or `web-production` profiles.
`fileReplacements` is a key entry in `angular.json` file defined in each profile.

For example, with `web` profile :
```json
 "fileReplacements": [
    {
      "replace": "src/environments/environment.ts",
      "with": "src/environments/environment.web.ts"
    }
  ]
```
The `fileReplacement.with` files contains a `web` part that match the pattern and change the `config.target` to `web`

This has to be done to make the application build with webpack with a web target only (ie. Browser). Otherwise webpack make the build failed.
Have a look at the npm scripts, you will see when those differents profiles are used. 
You will also notice that `electron-renderer` is set when you only want to build your application in order to run it in Electron.

**Comment by MMcKester** [comment]
Thanks a lot for the reply! That sheds some light on it. 

Looking at the debug config of VScode the "Application Debug" command calls `ng:serve` behind the scenes, therefore `-c web`.

<img width="247" alt="Screen Shot 2022-09-15 at 7 45 59 PM" src="https://user-images.githubusercontent.com/57302913/190527522-5c3add12-a9a3-42f3-9de9-4e3648bece13.png">


Once executed Electron + a web browser opens. Does this mean that in **this** mode the browser version is running even in Electron? And does this mean to get an "actual/real" debug Electron package I would need to go with `electron:serve-tsc/electron:serve` instead?

**Comment by maximegris** [comment]
It is because the debug config of VScode calls `npm start`. In dev/debug mode, the Electron app open a browser windows on http://localhost:4200. In that case, webpack has to build your app in `web` mode because your Angular source code isn't embeded directly in Electron. 

However when you run the other scripts `electron:local` or `electron:build`, you generate an Electron application. 
Your Angular files are embeded and  displayed from your Electron ASAR application and so have to be build with `electron-renderer`
.

**Comment by MMcKester** [comment]
That is an excellent answer, thanks a lot!
