### ISSUE TITLE
Enable context isolation for better security in Electron

### ISSUE THREAD

**Issue by thamizh-qwerty** [maximegris/angular-electron#745]
Hello,

I noticed that the "angular-electron" project does not enable context isolation, which could potentially lead to security vulnerabilities. According to the Electron documentation, enabling context isolation provides an additional layer of security by preventing renderer processes from accessing the main process directly.

I would like to request that the "angular-electron" project enable context isolation in order to improve the security of the application. This can be done by setting the "contextIsolation" property to "true" in the Electron configuration.

Thank you for your attention to this matter.

**Comment by maximegris** [comment]
Hi

I agree but in this scenario, it's obvious the developer needs to spend more effort on the electron side of the project because he/she needs to write there all the middle-layer logic to interact with node_modules libraries.
The purpose of this project is to stay as simple as possible and migrate to contextIsolation is not that hard if you follow the official documentation. That's why it's not enabled currently.

But I can change my mind and your PR is welcomed :)

**Comment by thamizh-qwerty** [comment]
@maximegris 

Hi, 

Currently working on an electron project. After completing that successfully, I will ping you with a PR. The PR will contain codes from below projects. Instead of react, we gonna play with Angular.

1. https://github.com/reZach/secure-electron-template
2. https://github.com/desktop/desktop

Feel free to close this issue. I will come back soon.
