### ISSUE TITLE
Images in template html / webpack problem

### ISSUE THREAD

**Issue by raczak** [maximegris/angular-electron#8]
Hello thx for your previous answer :) ,

I also have others issues :

I have a custom js script and unfortunately I need to reuse it in a template. How can I import it without using a : `<script src="myscripts.js"></script>` in the template.

The second problem is also related to the tempale : I want to know how can I display images in my template. For example in `index.html` I want to add a svg and a png image from my assets folder. But when I put the `<img>` tag with the correct path after a `webpack --watch` the image is not found. Webpack don't add my image to the dist folder. My assets are in `src/assets`.

Thank you by advance for your answer,

**Comment by maximegris** [comment]
Default webpack configuration don't process html and just load it as is.

There is actually an opened issue about using html-loader instead of raw-loader https://github.com/angular/angular-cli/issues/5363

If you want to changge webpack config, you have to install "html-loader"  : `npm install -D html-loader`and replace `:
      {
        "test": /\.html$/,
        "loader": ["html-loader"]
      },

by 


About your script, you need to:
- add `allowJs: true` in tsconfig.ts
- `import './test.js'` in `àpp.component.ts`
